name: Run nanDECK and Upload Export

on:
  workflow_dispatch

jobs:
  build-nandeck:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Ruby for Fontist to successfully download
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.0.0"
    - name: Setup Fontist to Download Fonts
      uses: fontist/setup-fontist@v2
      with:
        fontist-version: "2.0.3"

      # Remember to update this next line whenever we add fonts
    - run: |
        fontist install "Inter"

    - name: Export main deck
      run: |
        .\nandeck\nanDECK.exe .\nandeck\decks\cards.txt /exec
      shell: cmd
      
    - name: Upload Export Folder
      uses: actions/upload-artifact@v4
      with:
        name: nandeck-export
        path: nandeck/export
        retention-days: 1
